// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "calculator.com/internal/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// GetProducts provides a mock function with given fields: ctx, IDs
func (_m *ProductRepository) GetProducts(ctx context.Context, IDs []string) ([]dto.Product, error) {
	ret := _m.Called(ctx, IDs)

	var r0 []dto.Product
	if rf, ok := ret.Get(0).(func(context.Context, []string) []dto.Product); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
