apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      name: calculator
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: gcr.io/go-test-346819/calculator:latest
          ports:
            - containerPort: 8080
